services:
  - type: web
    name: foxcoin-userbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python foxcoin_userbot.py
    envVars:
      - key: PORT
        value: 8080
